### ISSUE TITLE
I think that maybe you can set the lrc-background from #fff to transparent?

### ISSUE THREAD

**Issue by ZengShuai1996** [DIYgod/APlayer#100]
Do you think so?

**Comment by DIYgod** [comment]
Why you need transparent?

**Comment by ZengShuai1996** [comment]
Maybe i'm a obsessive(强迫症患者)=-= and my web is translucent(半透明的)

**Comment by ZengShuai1996** [comment]
Maybe i'm a obsessive(强迫症患者)=-= and my web is translucent(半透明的)
