### ISSUE TITLE
一个页面多个音频有BUG，但是秒不走，声音也没有

### ISSUE THREAD

**Issue by yoursian** [DIYgod/APlayer#101]
一般第一个正常，第二个超20分钟大概5MB-10MB左右的音频。加载完，无法播放。

**Comment by yoursian** [comment]
1.5.8 的版本这个问题比较严重。1.5.7的问题很少发生、但是list播放会无限循环。。。在mobile端

**Comment by DIYgod** [comment]
Can you give a demo page?
