### ISSUE TITLE
中文说明。

### ISSUE THREAD

**Issue by WEI-KE** [DIYgod/APlayer#102]
能写份中文的说明不.....初中水平的英语看起来实在困难（努力学习中）。（给大佬递茶

**Comment by MoeGakuen** [comment]
世界上有叫[翻译]的功能。

**Comment by WEI-KE** [comment]
@MoeGakuen .....什么时候翻译软件准确率过95%以上我就不求人翻译了。

**Comment by MoeGakuen** [comment]
机翻后脑补啊

**Comment by WEI-KE** [comment]
@MoeGakuen 是你太牛了还是我太笨了，就靠现在的软件我怎么也脑补也不对.....尤其是有代码的情况下。

**Comment by DIYgod** [comment]
不管作为程序员还是初中生，英语都不应该差到对着翻译也看不懂的程度

如果你是初中生，应该注意孰轻孰重，在没有做好分内的事情之前，不建议写代码

**Comment by liwanglin12** [comment]
@DIYgod 很好你顺带连着我喷了🌚

**Comment by liwanglin12** [comment]
@DIYgod 另外你咋知道他初中

**Comment by journey-ad** [comment]
基础的使用只需要了解几个简单单词的含义，翻译工具完全可以胜任。示例代码文档中已经给出，不确定的参数可以自己修改尝试。
如果是在博客中使用，主流博客程序都有适配的插件。
