### ISSUE TITLE
你好,APlayer 是一个非常棒的javascript插件.想问支持几种格式的音乐

### ISSUE THREAD

**Issue by abin2011** [DIYgod/APlayer#103]
可以支持ape 或者flac吗

最最重要的 是否打算支持 mid 格式呢...
因为歌曲涉及版权问题....但是目前mid格式还没有影响.

**Comment by liwanglin12** [comment]
@abin2011 好像diy试过没成功

**Comment by abin2011** [comment]
哦,那真是遗憾.
谢谢你的回复.
