### ISSUE TITLE
请问有添加歌曲到播放列表的api吗？

### ISSUE THREAD

**Issue by tonyski** [DIYgod/APlayer#104]
因为我不想刷新页面或者重新new APlayer

**Comment by fengT-T** [comment]
我也这么想

**Comment by fengT-T** [comment]
所以还请务必加上这个重要的api

**Comment by DIYgod** [comment]
It's a great suggestion, I will do it when I have some time.

**Comment by liwanglin12** [comment]
@DIYgod I'm so sorry to tell you this, but in fact, if @DIYgod say "sometime", that's means never.
😞

**Comment by metowolf** [comment]
@liwanglin12 It means sometimes **naive**...🌚

**Comment by liwanglin12** [comment]
@metowolf Magic of nature, the continuity of lasting🌚

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/APlayer/commit/cbc0f99eeeb1fefdf574892fbb607a8925742697

**Comment by metowolf** [comment]
(悲喜交加

**Comment by liwanglin12** [comment]
@DIYgod 女装啊！女装！太遗憾了！
