### ISSUE TITLE
会存在这样的问题嘛？音频格式问题

### ISSUE THREAD

**Issue by yoursian** [DIYgod/APlayer#106]
不是所有的浏览器都支持mp3，会存在不支持格式的播放？

**Comment by journey-ad** [comment]
就目前来讲除 Opera Mini 之外所有主流浏览器均支持 mp3 格式，具体可参见http://caniuse.com/#search=mp3

**Comment by yoursian** [comment]
Thanks ,压缩过的音频损耗对于兼容性方面有问题嘛。大狭

**Comment by DIYgod** [comment]
mp3是HTML5原生支持的，一般没有问题
