### ISSUE TITLE
A BUG on Safari?

### ISSUE THREAD

**Issue by ZengShuai1996** [DIYgod/APlayer#108]
If one of my songs is end and i'm looking at another label of Safari,Aplayer won't play next song.

**Comment by DIYgod** [comment]
It seems that Safari forbid autoplay audio in background.

**Comment by nceliy** [comment]
https://aplayer.js.org
this demo doesn't show the duration,  In my project also doesn't show the duration too. can you?

**Comment by ShawnZeng1996** [comment]
In my project it can. Are you using the narrow mode? @Or can you give the url of you project? @nceliy

**Comment by nceliy** [comment]
you can try this demo in the safari.
https://aplayer.js.org
![1111](https://user-images.githubusercontent.com/12245869/34980293-02c983ce-fadf-11e7-86bb-ea10f6e5a015.png)

**Comment by ShawnZeng1996** [comment]
Click the play button than click the button under it, such as 'ap.play()', 'ap.play(100)'. @nceliy

**Comment by nceliy** [comment]
i has tried according to your steps,but it doesn't work.oh.. , i use safari in window system,what you?

**Comment by ShawnZeng1996** [comment]
Oh……I use it on mac.Few people use safari on window……How about trying another browser on window? @nceliy

**Comment by DIYgod** [comment]
Safari for Windows is discontinued in 2012, maybe you should try another browser.

**Comment by nceliy** [comment]
oh,oh..other browsers are ok expect the ie ,because  the wav audio doesn't play in the ie browser.
thank you very much
