### ISSUE TITLE
Outsource styling in actual CSS file

### ISSUE THREAD

**Issue by Tekanewa** [DIYgod/APlayer#114]
While it isn't a problem if the overall DOM structure of the player is created by the JS routine, I think it is bad practice to have the full CSS styling for the player dynamically injected into the site via the JS routine, rather than having a dedicated CSS file.

Having a dedicated CSS file would also make it much easier to customize certain aspects of the player layout directly.

Other than that, this is a great little player!

**Comment by DIYgod** [comment]
You should not edit compiled CSS file directly, the proper way is to edit original CSS file.

Dynamically injecting is a common practice, which can make APlayer easier to use, especially in componentized project.
