### ISSUE TITLE
播放器不能放在 form 表单里

### ISSUE THREAD

**Issue by tsrh** [DIYgod/APlayer#115]
播放器不能放在 form 表单里，放在 form 表单里点击播放按钮的话会提交表单，测试官方实例也有这问题，有办法解决吗？

**Comment by liwanglin12** [comment]
@tsrh 为什么要放在form里

**Comment by tsrh** [comment]
给文章添加音乐搜索播放，比如搜索百度音乐把音乐抓取过来，给显示出来，但是在页面里不能点击播放，点击就提交表单

**Comment by liwanglin12** [comment]
@tsrh 你参考下 music.i-meto.com 看看

**Comment by tsrh** [comment]
@liwanglin12 他这个我最早看到的，他是搜索点击提交跳转到新页面播放的

**Comment by DIYgod** [comment]
Can you provide a demo page?

**Comment by tsrh** [comment]
@DIYgod 本地测试的，你可直接在你提供的 demo 页里的播放器放在 form 中，点击播放就提交表单了

**Comment by DIYgod** [comment]
Fixed. https://github.com/DIYgod/APlayer/commit/d381582fe427b3988c5b20da256e2b41f2e17372

**Comment by liwanglin12** [comment]
@DIYgod please merge this commit to Hermit-X 😄👍
