### ISSUE TITLE
怎么没有开源的？

### ISSUE THREAD

**Issue by liuyezaici** [DIYgod/APlayer#116]
很多需求想自己DIY一下，比如：
歌曲超过30首，列表何以翻页？
我想移除列表中的歌曲，如何操作ajax.
我想移动列表的歌曲
我想在列表中加入一些自己的元素，比如 收藏
我想改为jquery版
...

或者是我打开方式不对 如何查看原版的？

**Comment by liwanglin12** [comment]
@liuyezaici …… excuse me？

**Comment by metowolf** [comment]
https://github.com/DIYgod/APlayer/blob/master/src/APlayer.js
这玩意就是原版，编译方法 README 有

**Comment by liuyezaici** [comment]
我试试，第一次玩这个

**Comment by liuyezaici** [comment]
要不谁发个原版 我没有编译过JS···

**Comment by liwanglin12** [comment]
@liuyezaici

**Comment by kn007** [comment]
我第一次看到如此的伸手党。。

**Comment by liuyezaici** [comment]
可以给你转支付宝 要多少？

**Comment by G-monitor** [comment]
= =MDZZ..  
你是要这个么：https://github.com/DIYgod/APlayer/blob/master/dist

**Comment by liuyezaici** [comment]
这个压缩了，要原版的还要研究什么npm 运行什么鬼?

**Comment by G-monitor** [comment]
源码上面发过了，编译后成品是我发的那个

**Comment by liuyezaici** [comment]
打开看了 ，没找到 - -``

**Comment by G-monitor** [comment]
源码（开发时用的、“原版”）：https://github.com/DIYgod/APlayer/blob/master/src/APlayer.js
成品（在页面上引用的时候用的、压缩后的）：https://github.com/DIYgod/APlayer/blob/master/dist/APlayer.min.js

![一脸智障](https://cloud.githubusercontent.com/assets/11240579/22619162/55930934-eb29-11e6-99ff-3ae9b69993ae.jpg)

**Comment by MittWillson** [comment]
少年你好溜

**Comment by fly3949** [comment]
1. If you like, you can do it by yourself, but nobody has his duty to help you for your own idea.
2. This is github, which is an open source software community. Before you make an issue, please make sure you have known the rules of it.
3. The usage of npm is on README.MD, just follow it.
4. I think learning how to use npm is easy and helpful. So....try to learn it?

**Comment by liuyezaici** [comment]
require('./APlayer.scss'); 这个是原版js? 网页能运行么

**Comment by liwanglin12** [comment]
好大家都静一静，作者发话了 
![51baf40001cc4272086f5e925b6e7be1.png](https://img.cdn.lwl12.com/images/2017/02/04/51baf40001cc4272086f5e925b6e7be1.png)

**Comment by kn007** [comment]
太少了 @DIYgod ...

**Comment by liuyezaici** [comment]
我也只是侥幸问下 如果觉得原版不能公开直接说就好 这个和伸手扯不上关系，我又不是强行要资源。我开始也以为是编译问题。

**Comment by kn007** [comment]
兄弟，你在一个开源项目索要一个已经开源了源码。。还说要原版。。有点那啥。。

**Comment by G-monitor** [comment]
> 我也只是侥幸问下 如果觉得原版不能公开直接说就好 这个和伸手扯不上关系，我又不是强行要资源。我开始也以为是编译问题。

可是这个项目已经把所有的东西全部开源了，作者没有保留任何东西啊。。你要的东西已经在项目里有了
反而是我们没有理解你要的“原版”是什么东西。

**Comment by liuyezaici** [comment]
就是想问下有没有能直接运行的版本和jq一样 有mini版和full版。就是full版直接可以运行和修改的。

**Comment by liwanglin12** [comment]
@liuyezaici 老哥这个不叫原版……

**Comment by liuyezaici** [comment]
开发版？

**Comment by fly3949** [comment]
@liuyezaici 
作者没发编译好但是未经压缩的 js 代码文件，可能是懒...或者有他的顾虑？
npm的使用也不难，几行命令都写在 READ.ME 上面了。
这个标题反应了你知识水平不够高，毕竟这上面的都是开源项目（雾）。
不过讨论区戾气也是有点重...更希望你能自己编译一下，或者说发一个issue问下能否提供未经压缩但是编译好的代码。一上来就问有没有“原版”，比较容易被喷。
还是要提高自己的姿势水平，闷声发大财，系唔系得噶？

**Comment by kn007** [comment]
你的意思是要编译未压缩版本。。但那不叫原版。。源码才是真正意义的原版。。

**Comment by liwanglin12** [comment]
@fly3949 哦豁，被 fly 大佬印点了，尴尬

**Comment by liuyezaici** [comment]
现在就是在研究这个npm node.js都安装好了  一脸蒙蔽无从下手

**Comment by MittWillson** [comment]
你还是too young 毕竟也是会上Gayhub的人了 不提升自己的姿势水平就来Issue发言就有点naive了

**Comment by liwanglin12** [comment]
@liuyezaici Run in development

$ npm install
$ npm run dev

Make a release

$ npm install
$ npm run build

**Comment by liwanglin12** [comment]
@liuyezaici 照着输

**Comment by fly3949** [comment]
git clone 一下然后照着 README 敲几行代码就好啦。所以说还是要学习一个。

**Comment by liuyezaici** [comment]
真心不懂这些命令行 我专业是php  没有摸过这个··

**Comment by kn007** [comment]
...你好意思说你专业是php

**Comment by liuyezaici** [comment]
只能麻烦说详细点了 什么软件/环境运行的

**Comment by huihuimoe** [comment]
https://github.com/jquery/jquery/tree/master/src 
事實上你說的jq的源碼也是醬紫的，jq提供的未經壓縮的版本也是編譯出來的

**Comment by liwanglin12** [comment]
@liuyezaici http://bfy.tw/9tEz
http://bfy.tw/9tF1

**Comment by fly3949** [comment]
npm 的用法，具体可以 Google 一下，个人认为在项目的 issue 下不适合讨论这种话题。因为这是对于该项目的...

**Comment by SevenOutman** [comment]
楼上不要太着急，就是说他以前没有接触过 npm，你们说编译啊什么的一下就把他搞晕了。
@liuyezaici 你要的可能是这个 http://cdn.bootcss.com/aplayer/1.5.8/APlayer.min.js ，只不过它是像 `jquery.min.js` 那样压缩过的，基本无法阅读

**Comment by liwanglin12** [comment]
@SevenOutman 他想要这个的未压缩版本

**Comment by Jackeriss** [comment]
PHP 果然是世界上最好的语言，连命令行都不需要用的。

**Comment by liuyezaici** [comment]
APlayer.min.js 这个也是混淆压缩过的   个人没有接触过项目这块，网站都是自己开发，npm也是第一次听说···

**Comment by kn007** [comment]
@SevenOutman 能理解的，但是php也有composer啊。。
一句我专业是php，我服了。
而且他本来就是想要 已编译未压缩版本 ，还说原版。。

**Comment by kn007** [comment]
@liuyezaici 这个我只看出压缩，没看出混淆。

**Comment by liwanglin12** [comment]
http://bfy.tw/9tEz
http://bfy.tw/9tF1
求先去了解下相关知识

**Comment by fly3949** [comment]
所以说这就应该是楼主不懂 npm 的使用，然后敲了个很尴尬的标题发了个 issue 引发大家的不满的故事...
今天就是得罪了大家一下。

**Comment by liuyezaici** [comment]
意思还是要认认真真学习npm了···?

**Comment by SevenOutman** [comment]
@liuyezaici 对，是压缩过的。作者没有发布过未压缩的版本。但作者公开了源码，你可以阅读源码来获取你想要的信息。

**Comment by fly3949** [comment]
毕竟是个前端项目=-=
学习成本也不高嘛...玩前端的肯定要会的啊...

**Comment by liuyezaici** [comment]
是的 ，借助作者的一些技巧，我自己写一个jq版的好了。

**Comment by freejishu** [comment]
压缩过的解压不就是了，又没太多混淆
-------------我是分割线------------------------
啤酒饮料矿泉水 面包鸡蛋火腿肠

**Comment by MittWillson** [comment]
作为同是学 世界上最好的语言(PHP) 的人，建议你不要只会写PHP 无论是搭环境 还是偶尔搞下前端 都得要接触要会 特别是linux和命令行 当你接触了命令行就会接触各种各样的命令 像npm这种 我也没接触过什么 但是看文档就知道怎么用 怎么编译了 如果这时候出问题了 再来issue提问就不会很尴尬了
Ps: 以上这堆废话不适用于windows和队长

**Comment by huihuimoe** [comment]
@liuyezaici 如果要編譯一個未壓縮版本的話，不只要知道npm，還得知道webpack(
如果熟悉的話，改下配置然後編譯就可以得到你想要的

**Comment by G-monitor** [comment]
> http://bfy.tw/9tEz
http://bfy.tw/9tF1
求先去了解下相关知识

你这人怎么这么坏，天天拿着这网站给人发链接

@MittWillson 你不要搞事情。。我前端也基本不会

**Comment by liuyezaici** [comment]
我要开始怀疑人生了。

**Comment by huyinjie** [comment]
笑死我了

**Comment by huihuimoe** [comment]
@liuyezaici 嗯，很多前端天天都在懷疑人生(

**Comment by liwanglin12** [comment]
@liuyezaici 既然你说你已经成功部署好了node.js 和 npm 那么你只需要依照我们刚刚说了很多次的 readme 里面的那几行指令编译就行了……
在你编译之前先对我们刚刚指明的那一个源码也就是
https://github.com/DIYgod/APlayer/blob/master/src/APlayer.js
                                                            (git 主分支)  (源)   
这个文件进行你期望的修改。在完成后执行编译指令就能拿到可用的文件了。
还有哪不懂？整个过程只有两条你需要新学的指令了

**Comment by liwanglin12** [comment]
而且还是照抄的

**Comment by fly3949** [comment]
本来学一下 npm 用法然后敲两行代码就好的事情....作为程序员掌握一下，相信也不用花多少时间成本。你是不是怀疑人生/前端和这个项目真的没什么关系...所以没必要再讨论了啊....
如果说是抱着不想花时间精力学新玩意儿的想法，那...也就无fuck说了=-=

**Comment by liwanglin12** [comment]
@fly3949 哪里需要学一下npm用法，他说环境都建好了那不就是copy paste的问题了

**Comment by freejishu** [comment]
不要抨击人家了，人家在怀疑人生，idioctonia就不好了
-------------我是分割线------------------------
啤酒饮料矿泉水 面包鸡蛋火腿肠

**Comment by fly3949** [comment]
@liwanglin12 那认真读完 README ，照着说明写两句呗。
-1s

**Comment by MittWillson** [comment]
没有关系 程序猿总有那么几天要怀疑猿生的 不怀疑猿生的程序猿不是好程序猿

**Comment by xiao201261** [comment]
@liuyezaici 所以你在问GitHub的代码不开源么...

**Comment by fly3949** [comment]
@xiao201261 他是因为没看到编译好而且未经压缩的源代码，所以认为项目没有开源。显然没有明确“开源”的相关概念。说到底还是姿势水平的问题..

**Comment by kn007** [comment]
@fly3949 兄弟态度挺好的，点个赞。

**Comment by liwanglin12** [comment]
@kn007 人家是长者，不会轻易的 angry

**Comment by huihuimoe** [comment]
@liwanglin12 偏題了，可以close了吧(

**Comment by liwanglin12** [comment]
@huihuimoe 通知DIY了啊，他节后综合征暂时不想看代码（相关）

**Comment by kn007** [comment]
其实我只想说，你们看看楼主1楼说的，那么多需求，不懂代码，他是怎么做到的？！
还要改成jquery版。。我没看明白。

**Comment by fly3949** [comment]
=-=好了好了 楼太歪了....

**Comment by huyinjie** [comment]
其实我想知道LZ是不是来搞笑的

**Comment by kn007** [comment]
一开始看到标题，还以为搞事情，说盗版了没保留信息，进来真是哭笑不得。。

**Comment by aofall** [comment]
我是来看"源码没开源的"的

讲真我觉得README已经讲的很清楚了

还有就是不要认为自己是PHPer就不需要学其他东西

技多不压身
