### ISSUE TITLE
播放列表条目溢出，歌手错位 Overflowing playlist item makes artists misplaced

### ISSUE THREAD

**Issue by vhyme** [DIYgod/APlayer#118]
用的是163music-APlayer-you-get-docker，不知道是不是版本问题：
![cd743993-b70e-4704-ad6b-7469b49ded64](https://cloud.githubusercontent.com/assets/5051300/22765905/a22ba436-eead-11e6-89e6-1a9779ad7769.png)
图上画圈的是一首歌的信息，可以看到有一首歌名太长，把自己的歌手挤到下一行了，然后下一行的歌手就被挤到下下一行了，直到遇到某一行能容纳两个歌手才恢复。

亲测在 .aplayer .aplayer-list ol li { 里面加 overflow: hidden 即可，不过这一行的歌手就被挤没了。

**Comment by DIYgod** [comment]
的确是版本问题，最新版本没有这个问题
