### ISSUE TITLE
Theme color self-adaption based on album cover

### ISSUE THREAD

**Issue by jisuwugui** [DIYgod/APlayer#119]
![image](https://cloud.githubusercontent.com/assets/16898790/22788082/731f3646-ef19-11e6-85cf-289c3c7738d5.png)
![image](https://cloud.githubusercontent.com/assets/16898790/22788085/76e0e202-ef19-11e6-8f90-7fa95306924d.png)
![image](https://cloud.githubusercontent.com/assets/16898790/22788089/7b5a8ea0-ef19-11e6-8091-2d7a45d2b2c2.png)

**Effect indicated above** (currently use back-end application to achieve)
So maybe this feature can be added, I guess. LOL

**Comment by DIYgod** [comment]
Good idea!

**Comment by DIYgod** [comment]
In consideration of simplifying design, I think it should not added into APlayer core, it can be realized by setting different `theme` option.
