### ISSUE TITLE
Skin Aplayer for You

### ISSUE THREAD

**Issue by tuannvbg** [DIYgod/APlayer#120]
Skin Aplayer default
[http://i.imgur.com/d4YQaZG.png](http://i.imgur.com/d4YQaZG.png)
Skin Aplayer by tuannvbg@gmail.com
[img]http://i.imgur.com/wIleu4Y.png[/img]
Skin Aplayer by Doan Nguyen
[img]http://i.imgur.com/zdnEQPg.png[/img]
Skin Aplayer by Doan Nguyen v2
[img]http://i.imgur.com/PT9q6tt.png[/img]

**Comment by DIYgod** [comment]
Thanks.
