### ISSUE TITLE
Player object create on id based can this class based....

### ISSUE THREAD

**Issue by imrantune** [DIYgod/APlayer#121]
Hi @DIYgod 

This is awesome player thanks for this .
I just want to it class based because if there is multiple same track on different places one page its just work for first id other places progresses bar not working 
is it possible to move this class base selector rather than id...

thanks you again for this

**Comment by DIYgod** [comment]
I can't understand you well, can you paste your code or give me a demo page.

**Comment by imrantune** [comment]
I am asking about javascript selector its dive id based ...
me just want to move on div class based selector ...
