### ISSUE TITLE
It should allow playlist could be a empty array,and the insert way should be append rather than innerHTML 

### ISSUE THREAD

**Issue by NE-SmallTown** [DIYgod/APlayer#124]
In most cases,we will initialize the aPlayer but dont' provide data to it because users don't click the play button on the song.After they click the play button,we will fetch the song data.But if the `music` property of aPlayer is an empty array,it will cause error,I check the src code,it seems that aPlayer don't consider this situation and just take data from the array.

On the other hand,aPlayer use `innerHTML` on the `element` property,but IMO,this is not appropriate because we have to create a container for aPlayer,if we use `appendChild` not `innerHTML` ,it would be better.

**Comment by liwanglin12** [comment]
@NE-SmallTown We received your issue. Please wait.
@DIYgod

**Comment by DIYgod** [comment]
I don't understand why you need a empty player. As I understand, you should initialize APlayer after click play button.

In next version, we will provide a API for changing music list.

Indeed, `appendChild` is a better way, thanks.

**Comment by NE-SmallTown** [comment]
@DIYgod Thanks for your reply.The reason of needing an empty array is that if we initialize APlayer after click play button,the user will be confused,they will say "Oops,there is not player,but when I click,it appears!",you can see the [qq music player](https://y.qq.com/portal/player.html)(try to clean all songs,you will see the player display well though there is no song)

**Comment by DIYgod** [comment]
You can initialize a player with a blank audio or a reminder audio before click.

**Comment by NE-SmallTown** [comment]
Ok,I will afresh consider this later.Thanks.

By the way,my option is:

```
this.aPlayer.player = new APlayer({
      element: this.aPlayerContainer, // Optional, player element
      narrow: false, // Optional, narrow style
      autoplay: false, // Optional, autoplay song(s), not supported by mobile browsers
      showlrc: 0, // Optional, show lrc, can be 0, 1, 2, see: ###With lrc
      mutex: true, // Optional, pause other players when this player playing
      theme: '#e6d0b2', // Optional, theme color, default: #b7daff
      mode: 'order', // Optional, play mode, can be `random` `single` `circulation`(loop) `order`(no loop), default: `circulation`
      preload: 'metadata', // Optional, the way to load music, can be 'none' 'metadata' 'auto', default: 'auto'
      listmaxheight: '200px', // Optional, max height of play list
      music: this.aPlayer.songList
    });
```

When I click the play button on one song,execute below:
```
this.aPlayer.songList[this.aPlayer.songListGuid++] = {
              title: songInfo.title,
              author: songInfo.singerName, // Required, music author
              url: songInfo.audioSrc, // Required, music url
              pic: songInfo.pic // Optional, music picture
            };

            this.aPlayer.player.setMusic(this.aPlayer.songListGuid - 1);
            this.aPlayer.player.play();

```

The pic and title and author shows well,but the song played is previous,I don't check aPlayer src code,but I think that's because aPlayer doesn't treat songList(i.e.,`music` property of aPlayer) dynamically?

**Comment by DIYgod** [comment]
I will provide a API for changing music list in next version.

**Comment by NE-SmallTown** [comment]
Hope for that.Thanks.

**Comment by NE-SmallTown** [comment]
@DIYgod Sorry for bothering you again,I try to use some ways to solve dynamical songList,but the only way I find is that initialize aPlayer every time I click the play button of one song(I thinks it is a big performance problem),if I just push the song into the array and call `setMusci(index)`,the aPlayer will throw error.I want to know that whether I use aPlayer correctly?Thanks.

**Comment by DIYgod** [comment]
Changing music list is irrealizable now.

**Comment by NE-SmallTown** [comment]
Yup,waiting for your good news!
