### ISSUE TITLE
About the "preload: 'metadata'"

### ISSUE THREAD

**Issue by yingshaoxo** [DIYgod/APlayer#126]
Can the APlayer don't ask for mp3 URL until someone click the play button?

That should be preload=False

But I don't know exactly what args use in here.

If preload always True, the web visiting won't be smooth enough.

Please give me an answer, thanks.

**Comment by fly3949** [comment]
[](https://aplayer.js.org/docs/)

> preload: 'metadata',    // Optional, the way to load music, can be 'none' 'metadata' 'auto', default: 'auto'

**Comment by DIYgod** [comment]
Read the Docs.
