### ISSUE TITLE
The ended event doesn't work

### ISSUE THREAD

**Issue by Blackmamba-xuan** [DIYgod/APlayer#135]
HI !
I found an issue when i try to add 'ended' eventlistener.Then , I copy the js from demo and it doesn't work too。Can you tell me what's wrong with my code?
eg:
var ap1 = new APlayer({
    element: document.getElementById('player1'),
    narrow: false,
    autoplay: false,
    showlrc: false,
    mutex: true,
    theme: '#e6d0b2',
    preload: 'metadata',
    music: {
        title: 'Preparation',
        author: 'Hans Zimmer/Richard Harvey',
        url: 'http://devtest.qiniudn.com/Preparation.mp3',
        pic: 'http://devtest.qiniudn.com/Preparation.jpg'
    }
});
ap1.on('ended', function () {
    console.log('ended');
});

**Comment by hu-qi** [comment]
I also encountered the same problem, how do you solve it?

**Comment by fly3949** [comment]
Could you provide a demo address for us?

**Comment by DIYgod** [comment]
Notice that the `ended` event only triggered when the player mode is `order` and all music finished(means that no more music will be played).

**Comment by hu-qi** [comment]
But in the mobile thre `order` failure.
`
 window.TMC.ap[$this.data.aid] =
            this.data.itemData.music ?
            new APlayer({
                element: document.getElementById('player_' + $this.data.aid),
                narrow: false,
                autoplay: true,
                mutex: true,
                theme: '#ad7a86',
                mode: 'order',
                music: this.data.itemData.music
            }) :
            new APlayer({
                element: document.getElementById('player_' + $this.data.aid),
                autoplay: true,
                narrow: false,
                mutex: true,
                mode: 'order',
                music: [{
                    title: this.data.itemData.name,
                    author: 'StartAI',
                    url: this.data.itemData.path,
                    pic: "./www/" + coverImg
                }]
            });
...
        window.TMC.ap[$this.data.aid].on('ended', function () {
            console.log('ended')
            $this.callback && $this.callback({
                aid: $this.data.aid,
                itemIndex: $this.data.itemIndex
            });
        })
        window.TMC.ap[$this.data.aid].on('play', function () {
            console.log('play')
        })
        window.TMC.ap[$this.data.aid].on('play', function () {
            console.log('play play')
        })
        window.TMC.ap[$this.data.aid].on('pause', function () {
            console.log('pause')
        })
        window.TMC.ap[$this.data.aid].on('canplay', function () {
            console.log('canplay')
            console.log('11')
            window.TMC.ap[$this.data.aid].play()
        })
        window.TMC.ap[$this.data.aid].on('playing', function () {
            console.log('playing')

        })
        window.TMC.ap[$this.data.aid].on('error', function () {
            console.log('error')
        })
`

the log:
`canplay                       index.js:1
11                                index.js:1
play                             index.js:1
play play                     index.js:1
31
playing                       index.js:1
655
playing                      index.js:1
pause 
`

**Comment by DIYgod** [comment]
I can't understand you. @hu-qi
