### ISSUE TITLE
Automatically switch to next song after finishing one song in mobile

### ISSUE THREAD

**Issue by immiao** [DIYgod/APlayer#138]
Could anyone tell me how to implement this?

**Comment by liwanglin12** [comment]
@immiao I reported this issue long time ago, but @DIYgod is too lazy to fix this.

**Comment by immiao** [comment]
@liwanglin12  Could you tell me the basic idea? I will try to fix it.

**Comment by liwanglin12** [comment]
@immiao Use only one audio tag to play all music. (change 'src' and other attitude if nessary)

**Comment by immiao** [comment]
@liwanglin12  Thanks so much!

**Comment by AnyListen** [comment]
这个JS代码里面有几处限制
1. 代码544行，此处判断如果是播放列表模式、且为手机端的话，则停止了播放；
```
if (this.multiple) {
                    if (this.isMobile) {
                        this.ended = true;
                        this.pause();
                        return;
                    }
```
2. 同样代码724与729行也做了限制；
```
        if (this.option.autoplay && !this.isMobile) {
            this.play();
        }
        this.option.autoplay = true;  // autoplay next music

        if (this.isMobile) {
            this.pause();
        }
```
首先需要把上述的限制去掉；此时可以测试是否已经可以连续播放，理论上是可以连续播放的，然而现实很残酷（具体情况没详细测试）；IOS系统出现不能自动下一首的问题，安卓高版本也会存在同样的问题，参考文章[手机的 HTML5 Audio 播放问题记录](http://www.86y.org/art_detail.aspx?id=720)，做一下修改：

对于代码471行，`if (!this.audios[indexMusic]) `的判断改为，`if (this.audio)`，也就是说当`this.audio`存在的情况下，不在重新新建`audio`，而是直接复用以前的，同时设置this.audio.src；
具体代码如下(代码为编译后的版本，由于不大会使用前段工具，所以在min.js上做的修改)：
```
this.audio ?  (this.audio.src = this.music.url, this.option.autoplay && this.audio.play(), 
        this.audio.setAttribute("title", this.music.title)) : 
        (this.audio = document.createElement("audio"))
```
play方法后面的是设置audio的title标签，该操作可以似的IOS锁屏界面限制设置的曲名信息；
效果可以参看：[鱼声](http://itwusun.com/)，经测试IOS可以在锁屏模式下播放下一首，安卓个人在模拟器测试的，貌似在锁屏状态下无法连续播放，非锁屏模式下可以

**Comment by liwanglin12** [comment]
@AnyListen @DIYgod 我去原来你自己还限制了，快点按这个改了！

**Comment by DIYgod** [comment]
Thank @AnyListen 

Done. https://github.com/DIYgod/APlayer/commit/dedcfbf1ac3aa3af4575d901c0db4dca8bc61619

**Comment by dansenpir** [comment]
@liwanglin12 Só por conseguir usar o PyCharm, tu já é vitorioso

**Comment by DIYgod** [comment]
@dansenpir English, please.

**Comment by liwanglin12** [comment]
@dansenpir Can't understand your comment.
