### ISSUE TITLE
Can you add next & previous button function? 

### ISSUE THREAD

**Issue by raselahmed7** [DIYgod/APlayer#17]
Missing next previous function on playlist mode. Can you add those? 

Thanks in advance.

**Comment by DIYgod** [comment]
Sorry, I think it is unnecessary, you can switch music by clicking playlist.

**Comment by WhiteFangWBC** [comment]
> Sorry, I think it is unnecessary, you can switch music by clicking playlist.

but if in ur playlist have a thounsand songs, so how we go the next random songs?
