### ISSUE TITLE
improve UI

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/APlayer#19]
1. click play list: toggle between play and pause
1. click picture: toggle between play and pause
1. more bolder play bar when hoverd or showed in mobile
1. hide buttons in narrow screen
1. adjust the position of lrc: below the picture
1. lrc rolling display
1. lrc show button
1. isMobile add wp

**Comment by nyaatyan** [comment]
Lyrics need expanding :joy: too small to completely see even only one sentence

**Comment by Alisummer** [comment]
😂
