### ISSUE TITLE
When the title is too long the artist name will be pushed to the next line

### ISSUE THREAD

**Issue by zgq354** [DIYgod/APlayer#22]
![5b0dc4e44785f7da](https://cloud.githubusercontent.com/assets/9024954/13200876/cb44b436-d895-11e5-9372-a62c66bc8deb.jpg)

**Comment by Copay** [comment]
应该做overflow处理,并且强制不换行

**Comment by DIYgod** [comment]
感觉这样隐藏掉也挺好，不修了2333
