### ISSUE TITLE
How to pause all musics on a page

### ISSUE THREAD

**Issue by hscale** [DIYgod/APlayer#24]
Hi all,
I want change url of a player by ajax reponse, but after load old audio still play, i mean too audios play same time.
How to pause all musics on a page?

Thanks.

**Comment by abdalrhman-alhomsi** [comment]
Hi,

Did you find any solution for that?

**Comment by DIYgod** [comment]
You can use pause API to pause a player. See [API](https://github.com/DIYgod/APlayer#api).
