### ISSUE TITLE
Long audio files over an hour long (DJ mixes) show as minutes

### ISSUE THREAD

**Issue by Rogue75** [DIYgod/APlayer#25]
Long audio files like DJ mixes don't show the hour designation. They show as minutes.
For example, 1:06:58 shows as 66:58.

PS, great player!

**Comment by Copay** [comment]
很正常......吧?

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/APlayer/commit/02058ad17fbef09799b9a06d4f8c52a731f7f953
