### ISSUE TITLE
How to pause first player when second player start?

### ISSUE THREAD

**Issue by Key7i** [DIYgod/APlayer#28]
Hi,

I can't figure out how the first player can be paused if second, third or any other player starts playing.

Can you tell  me with an example code? Demo page also doesn't stop any other player.

Thanks for your efforts. It's a great player indeed.

**Comment by DIYgod** [comment]
Fixed, see https://github.com/DIYgod/APlayer/commit/f013a39d6477298ae1812aa1cd11835418af717b
