### ISSUE TITLE
手机浏览器中不自动播放

### ISSUE THREAD

**Issue by starock** [DIYgod/APlayer#32]
即便是在init参数中将autoplay设置为true也不能自动播放；甚至在init()后再次调用play()方法也不行。

上述问题在PC浏览器不存在，在手机上会发生（安卓和iOS局势如此）。

求解决办法，多谢！

The player can't auto play in mobile bowser. Even set init param(autoplay is ture) , it still can't auto start.

help, thx~!

**Comment by starock** [comment]
调了一晚上，iOS上始终不正常T_T  只好暂时放弃了。

**Comment by journey-ad** [comment]
因为移动设备本来就无法在没有用户操作的情况下自动播放，安卓端某些应用内置浏览器除外

**Comment by journey-ad** [comment]
因为移动设备本来就无法在没有用户操作的情况下自动播放，安卓端某些应用内置浏览器除外

**Comment by DIYgod** [comment]
@journey-ad 正解，规范规定移动端不能自动播放，所以移动端浏览器做了限制，这个问题无解

**Comment by walterjunjun** [comment]
可以看一下这个讨论：http://stackoverflow.com/questions/25023211/html5-audio-why-not-working-on-ios-no-autoplay-involved

好像是code可以解决的。 期待你能更新。

**Comment by DIYgod** [comment]
@walterjunjun 请仔细看：To play audio/video on mobile devices you need direct, physical and synchronous interaction from the user. 

目前不可能做到做自动播放，因为W3C规范有规定。

**Comment by walterjunjun** [comment]
对，这个是我忽视了。我还有一个问题，就是我播放几首歌曲时候，iphone不会自动播下一首歌，而电脑chrome用起来自动播放下一首是可以。这个你知道如何解决吗

**Comment by walterjunjun** [comment]
那个webpage只有一个player，我试了你的demo，也是不能自动播放下一首。

**Comment by DIYgod** [comment]
@walterjunjun 同样的问题啊，移动端不能自动播放，无解

**Comment by walterjunjun** [comment]
http://kolber.github.io/audiojs/demos/test6.html
iphone can autoplay next song

**Comment by DIYgod** [comment]
[SoundJS](https://github.com/CreateJS/SoundJS)使用Flash实现了移动端的自动播放

有兴趣可以参考下

自动播放体验很差，特别是移动端，我这里不打算支持了
