### ISSUE TITLE
Songs with even number are automatically skipped

### ISSUE THREAD

**Issue by Wildog** [DIYgod/APlayer#33]
Songs with even number are automatically skipped in Safari but not in other browsers, FYI I'm using Safari 9.1 on OS X 10.11.4. Plus the progress bar's click zone is so narrow thus making it hardly clickable.

**Comment by DIYgod** [comment]
Fixed in https://github.com/DIYgod/APlayer/commit/7b8ad10c04d2264a482a2a420bd9f11b3a79c5d5.

Thanks.
