### ISSUE TITLE
Play music over diffrent tabs

### ISSUE THREAD

**Issue by SimonMattila** [DIYgod/APlayer#34]
I would love if anyone here could tell how I can make the music play over diffrent pages/tabs on the same domain, where I can just go to a diffrent sub-url and it will keep playing, sessionstorage perhaps? And how do I set default volume to 50%? Thanks

**Comment by DIYgod** [comment]
Keep playing: try ajax loading rather than refreshing page.

Set default volume: I will make a volume api later.
