### ISSUE TITLE
IE下报错，Symbol未定义 (Uncaught ReferenceError: Symbol is not defined)

### ISSUE THREAD

**Issue by efeencheung** [DIYgod/APlayer#42]
抛出异常 Symbol 未定义，在win10 edga 下正常 其他都报错

**Comment by efeencheung** [comment]
刚才用IE浏览器访问了下 Demo 也是报错

**Comment by DIYgod** [comment]
抱歉，暂时没有兼容IE浏览器的计划

**Comment by efeencheung** [comment]
好吧 大叔我自己搞掂吧，小鲜肉就是任性

**Comment by DIYgod** [comment]
😂👍

**Comment by efeencheung** [comment]
关于 Symbol 未定义，可能是在build的时候有依赖没有加载的问题。我折腾了半宿没搞定，对前端也不精，你看下这个[讨论](https://github.com/babel/babel-loader/issues/84)，还有一个兼容性问题就是 ie 的 audio api 在play执行前必须load，在你play方法里面加上this.audio.load()就可以了。项目太着急了，没办法，我就把你的事件相关代码都注释掉重新build了一下，你要是有空的话就看看，没空的话，等大叔项目结束了再折腾吧

**Comment by efeencheung** [comment]
主要问题 出在  for of 循环上面

**Comment by WEI-KE** [comment]
哈哈哈，Safari也是不行的，微信自带也是不行的，目前只有chrome内核和edge可以

**Comment by DIYgod** [comment]
Caused by incompatibility of `for of` handled by Babel.

Fixed in https://github.com/DIYgod/APlayer/commit/47270238cb154eda576227c2cee812a1d9dbe032  .

Thanks.

**Comment by WEI-KE** [comment]
再告诉你个小问题，手机端的浏览器是不会自动播放的。![image](https://cloud.githubusercontent.com/assets/19319469/15269096/29bc5708-1a27-11e6-853f-3343d03821c5.png)

**Comment by DIYgod** [comment]
@WEI-KE 这个无解，浏览器做的限制，讨论：https://github.com/DIYgod/APlayer/issues/32

**Comment by WEI-KE** [comment]
手机端，试了一下循环播放也是失效状态，点击别的歌之后还要再点击播放，Safari，微信自带，chrome都一样

**Comment by wipphj** [comment]
IE Symbol 未定义解决
https://github.com/HubSpot/Singularity/commit/be3d1512cc09e84c9abff1e8444b4041de9b811d

**Comment by DIYgod** [comment]
@wipphj 我记得解决了呀，现在还有这个问题么？

**Comment by wipphj** [comment]
@DIYgod 贴错地方了，哭

**Comment by huanglw** [comment]
使用for...of遇到了同样的报错！

**Comment by Copay** [comment]
@huanglw 您好，IE不支持Symbol的
