### ISSUE TITLE
preload issue

### ISSUE THREAD

**Issue by jiaghara** [DIYgod/APlayer#45]
please add preload enable and disable on Aplayer
this function will useful for server load 
thanks Admin for very very good Player

**Comment by DIYgod** [comment]
The default way of preload in APlayer:
- `metadata` in Desktop: indicates that only audio metadata is fetched.
- `none` in mobile: indicates that the audio should not be preloaded.

I think it's the best way to preload audio, and users don't need to set preload themselves. What do you think?

**Comment by jiaghara** [comment]
i think 
every small function are useful for developer
different developer using player on different ways   
i m using aplayer on my youtube to mp3 convertor so preload function is very important for me.
please add preload if it's not very hard for you 
thank in advance :)

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/APlayer/commit/12fc04957dc83ba771ea16c65c3e0a01f5fa3c1c.
