### ISSUE TITLE
Hover color should be configurable

### ISSUE THREAD

**Issue by Haocen** [DIYgod/APlayer#46]
Say, if the webpage theme is white text on dark(light on dark), then it can cause style problem.
Example:
<img width="707" alt="hover" src="https://cloud.githubusercontent.com/assets/10842569/15769608/a8604e86-292a-11e6-86c6-93e91fe659e1.png">

Currently hover color is hard coded:

>               &:hover {
>                    background: #efefef;
>                }

So is the background color of current item being played.
I think it would be great to make it configurable as an option, the implementation would be rather simple.

**Comment by DIYgod** [comment]
Sorry, I cannot meet the needs of all. This problem can be resolved by custom CSS:
```css
.aplayer .aplayer-list ol li:hover {
    background: #000;
}
```
