### ISSUE TITLE
play event not triggered if autoplay set to true

### ISSUE THREAD

**Issue by Haocen** [DIYgod/APlayer#47]
only `canplay` will be triggered.

tested on Chrome Version 51.0.2704.84 (64-bit)

**Comment by DIYgod** [comment]
To be consistent with native audio, play event should not triggered by autoplay.

**Comment by DIYgod** [comment]
I could not recreate the problem.
Can you get `play` in the console of `http://aplayer.js.org/`

**Comment by Haocen** [comment]
There is a logical problem in my code, which will result in events listeners remove from elements not being displayed, I believe that caused the problem.
