### ISSUE TITLE
Play from a specific time-point

### ISSUE THREAD

**Issue by gijsjager** [DIYgod/APlayer#49]
Hello! 
First of all this is a great plugin! But I am wondering if its possible to start the player from a specific time point? 

I want to load the plugin but when I refresh the page I can continue in the plugin where we left off.
I think this could be accomplished by an option like: 

`var option = {
start: 0 // start time in seconds (or miliseconds)
}`

Is this possible? (maybe its already possible)
Thanks in advance!

**Comment by rocalker** [comment]
I'm sorry,i collect the code only,and have not read the code ever.
But i think you can set autoplay to false,and play after seconds.

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/APlayer/commit/9f9ded6e1e7e1b76bc933be0dcbf449a5b95fb46

New API: [ap.play(time)](https://github.com/DIYgod/APlayer#api)
