### ISSUE TITLE
为列表增加随机播放功能

### ISSUE THREAD

**Issue by micooz** [DIYgod/APlayer#50]

**Comment by Jackeriss** [comment]
+1，建议把循环按钮换成在｛列表循环，单曲循环，随机播放｝间切换的按钮，就像网易云音乐一样。这样可以更好的迎合用户的使用习惯。加载时也可以设置默认的播放方式。

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/APlayer/commit/2d49e7aa76bfefd364eae571da20e311c2d69111

random: 随机播放
single: 单曲循环
circulation: 列表循环
order: 顺序播放（不循环）
