### ISSUE TITLE
music.pic 不支持带有空格或中文名称的链接

### ISSUE THREAD

**Issue by MrChu** [DIYgod/APlayer#51]
如下：
> http://7xvh1w.com1.z0.glb.clouddn.com/OK%20-%20%E5%BC%A0%E9%9C%87%E5%B2%B3.jpg

**Comment by DIYgod** [comment]
支持啊，demo里就有中文

**Comment by MrChu** [comment]
@DIYgod 音频文件链接支持中文，但是专辑图片不支持带有中文的链接，我都试了好多次了。。。

**Comment by DIYgod** [comment]
我的demo里有中文的例子，或者你给我个不支持的demo

**Comment by MrChu** [comment]
@DIYgod 临时链接，测试完请回复，我停止服务器。
demo：[http://me.tunnel.qydev.com/APlayer.html](http://me.tunnel.qydev.com/APlayer.html)
Pic Link：[http://7xvh1w.com1.z0.glb.clouddn.com/%E6%80%9D%E5%BF%B5%E6%98%AF%E4%B8%80%E7%A7%8D%E7%97%85%20-%20%E5%BC%A0%E9%9C%87%E5%B2%B3.jpg](http://7xvh1w.com1.z0.glb.clouddn.com/%E6%80%9D%E5%BF%B5%E6%98%AF%E4%B8%80%E7%A7%8D%E7%97%85%20-%20%E5%BC%A0%E9%9C%87%E5%B2%B3.jpg)

**Comment by DIYgod** [comment]
encodeURI的问题，把你已经转移的链接重复转义了，我知道了

**Comment by MrChu** [comment]
@DIYgod OK，那我停止本地服务器了，你可以另存demo网页源码，文件链接都是公开外链。

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/APlayer/commit/9f9ded6e1e7e1b76bc933be0dcbf449a5b95fb46
