### ISSUE TITLE
是否支持远程lrc？

### ISSUE THREAD

**Issue by zhouhao27** [DIYgod/APlayer#56]
是否可以通过url提供lrc？或者至少通过访问单独的lrc文件？谢谢

**Comment by DIYgod** [comment]
暂不支持，不过想法很好，以后会加上的，谢谢~

**Comment by zgq354** [comment]
我觉得ajax加载url的时候可能会出先跨域问题

**Comment by zhouhao27** [comment]
@zgq354 这是一个问题。不过我想可以先支持同域的lrc文件也很有帮助。

**Comment by DIYgod** [comment]
不同域的就没办法咯🌚

**Comment by Copay** [comment]
超赞API,fetch.跨域无问题,就是只兼容现代浏览器(包括EDGE14)

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/APlayer/commit/f91eba1aba9e255c77f382ed5b71e15a2e34f2c8
