### ISSUE TITLE
new fn setTrack();

### ISSUE THREAD

**Issue by realdark** [DIYgod/APlayer#61]
Hello,

Will be great if you add new fn`s to interact with the playlist. For example at the moment i need fn to set manual which track to play.

Example:
I have playlist with 5 tracks and i need to listen track 3 from 45s.

ap.setTrack(3);
ap.play(45);

Thx.

**Comment by DIYgod** [comment]
Thanks, I will optimize this problem in the next release.

**Comment by DIYgod** [comment]
`ap.setMusic(index)`
