### ISSUE TITLE
i  want to use ajax to change option ,but it seems doesn't useful in this way

### ISSUE THREAD

**Issue by fangcheng0724** [DIYgod/APlayer#62]
var option = {
    element: document.getElementById('player1'),
    narrow: false,
    autoplay: true,
    showlrc: false,
    mutex: true,
    theme: '#e6d0b2',
    preload: 'metadata',
    music: {
        title: 'Preparation',
        author: 'Hans Zimmer/Richard Harvey',
        url: 'http://devtest.qiniudn.com/Preparation.mp3',
        pic: 'http://devtest.qiniudn.com/Preparation.jpg'
    }
};

var ap1 = new APlayer(option);
ap1.init;
//it's useful as i use the dome ,but i don't know where is the problem

**Comment by DIYgod** [comment]
I do not understand, where is ajax?

Moreover, `ap1.init;` => `ap1.init();`

**Comment by Copay** [comment]
Where is AJAX????????

**Comment by teafn** [comment]
how can i add data( option.music ) from ajax to the option when the player's option has already been set
