### ISSUE TITLE
Tracks over 100 minutes not showing lyrics

### ISSUE THREAD

**Issue by TheElectroclassics** [DIYgod/APlayer#64]
DJ Sets over 100 with lyrics / set-list do not show on the viewer.

**Comment by DIYgod** [comment]
Sorry, I don not understand well, do you have a demo?

**Comment by Copay** [comment]
show a error snapshot?

**Comment by TheElectroclassics** [comment]
the-electroclassic.com.mx/set

When passing the mark of 100 minutes, the lyric viewer (where I placed my set list) it stops to update.

**Comment by Copay** [comment]
It seems OK.
Chrome 52.0 && Windows7

**Comment by DIYgod** [comment]
I could not recreate the problem, please provide your browser and OS info.

**Comment by TheElectroclassics** [comment]
Latest Version of Safari Mac OS X El Capitan 10.11.6
