### ISSUE TITLE
播放前10秒随机跳&&进度条跨越边界

### ISSUE THREAD

**Issue by komeiji-satori** [DIYgod/APlayer#65]
不知道怎么描述....也可能是我浏览器的问题
![qq 20160814170901](https://cloud.githubusercontent.com/assets/18225919/17648304/d61eeba2-6241-11e6-945b-83d4f2e9998c.png)

http://music.satori.moe/view.php?mid=31967335

**Comment by Copay** [comment]
诡异的错误
解决方法:不知道
建议等待Diygod的回复.
