### ISSUE TITLE
Optimize sorting algorithm for random mode

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/APlayer#77]

**Comment by liwanglin12** [comment]
@DIYgod @DIYgod 你们英语怎么都这么好啊！

**Comment by fly3949** [comment]
@liwanglin12 In fact, you just need some basic English knowledge and Google translate.
系唔系得噶？

**Comment by metowolf** [comment]
There are two options:

ONE
 1. Clone Index to Index2.
 2. Suffle Index2.
 3. use Index2 to switch next music

TWO
 1. Clone Index to Index2.
 2. when a song end, generate a random from Index2, set next to and delete it.
 3. if Index2 is empty (->1).
