### ISSUE TITLE
也许可以考虑使用iframe来获得更好的体验_(: 」∠)_

### ISSUE THREAD

**Issue by BlueCocoa** [DIYgod/APlayer#81]
有两个原因qwq

1. 在某些时候，APlayer的CSS会被当前页面的CSS覆盖
1. 使用iframe的话，可以像Disqus那样在任意页面都能呼出自己的overlay，对于APlayer来说，可以做成playlist或者之类的喵

**Comment by DIYgod** [comment]
有需要的话可以自己套一层啊，一样的

**Comment by BlueCocoa** [comment]
呜哇，好的

**Comment by DIYgod** [comment]
喵呜，那我关了
