### ISSUE TITLE
Player crashed when switching between musics within playlist 

### ISSUE THREAD

**Issue by rgconxol** [DIYgod/APlayer#83]
## I can't switch between musics within a playlist without crashing the player.
Your player is very beautiful and pretty mobile-friend. I really appreciate your work. 
Thanks to fix the bug related to the playlist. 
Thanks.

**Comment by DIYgod** [comment]
I have never encountered this situation, please tell me your OS and browser info, it would be better if you have a demo page or screenshot.

**Comment by rgconxol** [comment]
Here is a link to a screenshot: https://goo.gl/bNldLo
Thanks

**Comment by sabrinaluo** [comment]
+1, got below error, on your demo site.  `Chrome Version 54.0.2840.59 (64-bit)` with OS Linux Mint
```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()
```

Repro:
1. go to demo site http://aplayer.js.org/
2. Play `With playlist`, click item1, then click item2

**Comment by DIYgod** [comment]
I can reproduce this situation now, thanks.

I will fix it later.

**Comment by rgconxol** [comment]
Thank you  for your friendly support. 
May I know when I can expect this issue to be fixed. 
I would like to use your player in a projet that I'm working on. 
Thanks

**Comment by DIYgod** [comment]
I will fix it tonight (Chinese Standard time)

**Comment by rgconxol** [comment]
Awesome. 
Thank you so much
