### ISSUE TITLE
APlayer HTML5 Karaoke is great

### ISSUE THREAD

**Issue by tuannvbg** [DIYgod/APlayer#85]
I'm from vietnam. I have code music, I found APlayer via Google. I use APlayer HTML5 Karaoke with my code music (open source). Play song is ok but play playlits (Album) when switch song error. I hope founder APlayer fix soon! Demo: http://alovui.esy.es/playlist-lrc/Lien-Khuc-Tuan-Vu/EZEFZZ0-0.html

**Comment by DIYgod** [comment]
Thanks, fixed.

**Comment by Alisummer** [comment]
@DIYgod test
