### ISSUE TITLE
`play` event won't be triggered if `autoplay` = true

### ISSUE THREAD

**Issue by Haocen** [DIYgod/APlayer#87]
Tested on http://aplayer.js.org/
![image](https://cloud.githubusercontent.com/assets/10842569/19837259/6ea71274-9e8c-11e6-8eea-234900fde50b.png)

**Comment by ZengShuai1996** [comment]
Me,too.How to solve this problem?

**Comment by DIYgod** [comment]
Because the music has been started when binding play event.

To solve this problem, you can trigger it manual when binding play event.

**Comment by liwanglin12** [comment]
@DIYgod why 你们不说 chinese?

**Comment by Haocen** [comment]
@liwanglin12 in order to allow more people participate in this problem you're recommended to use English whenever you can.

@DIYgod the scenario I'm encountering is when user is visiting from mobile device, the `autoplay` option won't work, if I trigger the `play` event, it will result unexpected behavior.

My player will auto disappear after a certain amount of time if `pause` `error` or `ended` event is triggered.
Upon `canplay` it will show up and auto disappear after timeout.
If `play` event is not triggered properly, e.g. triggered while binding and `autoplay` set to true, then the player will never disappear if user is visiting from mobile devices.

**Comment by DIYgod** [comment]
@Haocen You can trigger it after a simple judgment:
```js
var ap = new APlayer(option);
ap.on('play', handler);
if (!ap1.audio.paused) {
    handler();
}
```

**Comment by Haocen** [comment]
@DIYgod Yeah I figured. But it would be great if you can put a fix in the code and ensure the following behavior:
1. `canplay` always triggered before `play`.
2. `autoplay` set to true always trigger `play` if audio actually start playing, regardless of the actual device.

I can make a PR for this if you don't mind.

**Comment by DIYgod** [comment]
Great suggestion.

It will be nice to make a PR, thanks.

**Comment by Haocen** [comment]
https://github.com/DIYgod/APlayer/pull/97

**Comment by Haocen** [comment]
@DIYgod 
The PR I made just then should had ensured following behavior:
1. `canplay` always triggered before `play`.
2. `autoplay` set to true always trigger play if audio actually start playing, regardless of the device.

However, I did some research and believe all the events that are supported by original HTML5 audio tag should be proxied instead of reimplemented, for example W3C claim that `playing` Fires when the audio/video is playing after having been paused or stopped for buffering.

Meanwhile I suggest we implement some lifecycle deducer to help maintain the state of player, regardless of the device and browser. The lifecycle deducer can allow additional events, for example `isPlaying`, `playStart`, `playToCertainLength` or other relative events, allowing for more precise control over the player.

This will result in breaking change for the event listeners, if you agreed with me we can branch off the `master` and work there.

**Comment by DIYgod** [comment]
@Haocen But I think these events are enough, and handling original audio(`ap.audio`) directly are supposed.

**Comment by Haocen** [comment]
Sure, I'd be more than happy to help you implement and test if you propose another way to fix the current behavior when `autoplay` set to true.

**Comment by Haocen** [comment]
Confirmed fix after https://github.com/DIYgod/APlayer/commit/0b0be17c70ac93de51e5599b603486df3f8fa104
