### ISSUE TITLE
APlayer can play video + lrc (or .srt, .vtt) and play Youtube (+lrc or srt)

### ISSUE THREAD

**Issue by tuannvbg** [DIYgod/APlayer#88]
I think APlayer play video + lrc. When APlayer is pefect player HTML5. APlayer can play Youtube, Vimeo?

**Comment by DIYgod** [comment]
I have an video player: https://github.com/DIYgod/DPlayer

**Comment by liwanglin12** [comment]
@DIYgod the Shortname is AD Player （escape~

**Comment by lyricsbd** [comment]
Aplayer or Dplayer not support youtube  @DIYgod  
can you add this feature?? @DIYgod
