### ISSUE TITLE
APlayer can change font size, font color

### ISSUE THREAD

**Issue by tuannvbg** [DIYgod/APlayer#95]
Thank you founder write APlayer. I think APlayer is future a :+1:  Player HTML5 one a more Player is great in the world. I like font color blue, red and bold for lrc-content. I try modify APlayer.min.js. Demo  http://baohiem.2fh.co/bai-hat/As-Long-As-You-Love-Me/EZFA06W.html. Thanks github.com, google.com (via goole, I known APlayer). Sorry my bad english.

**Comment by DIYgod** [comment]
I'm glad you like it.
