### ISSUE TITLE
Wordpress侧栏小工具使用Aplayer后，加载速度变慢

### ISSUE THREAD

**Issue by xmuplus** [DIYgod/APlayer#96]
1. 不使用Aplayer小工具首页第一次（已清除缓存）加载速度为500ms左右。
2. 使用Aplayer小工具后，首页第一次加载在4000ms左右。不知何故，望解答。谢谢！

**Comment by liwanglin12** [comment]
@xmuplus try https://lwl.moe/jSCv0

**Comment by DIYgod** [comment]
Maybe your music file is too big.

**Comment by liwanglin12** [comment]
@DIYgod so change preload attitude to no-Preload？

**Comment by DIYgod** [comment]
@liwanglin12 The better idea is leave it alone, for it has no effect on page.

**Comment by xmuplus** [comment]
@liwanglin12 In fact, the loading time was reduced to less than 2000ms after I changed `preload` to `none` in options. And music files comes from the samples you @DIYgod provide.
