### ISSUE TITLE
歌词没有进行自适应处理

### ISSUE THREAD

**Issue by 872517414** [DIYgod/APlayer#99]
![1](https://cloud.githubusercontent.com/assets/9050713/20647526/4c273ef8-b4d1-11e6-9c2a-7d60cae50752.png)
 放WordPress 小工具中的效果，可见歌词并没有完全显示出来。

**Comment by DIYgod** [comment]
这个实在没地方显示歌词了呀...

**Comment by SevenOutman** [comment]
@872517414 我建议你吧播放器换个宽敞的地方放…缩成这样本来也不怎么美观

**Comment by 872517414** [comment]
那能否设置不显示歌词？

**Comment by liwanglin12** [comment]
@872517414 please check readme.md

**Comment by 872517414** [comment]
README.md haven't how to be not displayed lyc in HTM,docs neither.

**Comment by liwanglin12** [comment]
showlrc: 0,

**Comment by DIYgod** [comment]
Fixed in https://github.com/liwanglin12/Hermit-X/commit/8d70e1fc1388e937334ebfe1a11adbd7a494f5ba
